"""add inventory tables

Revision ID: 8f17f5399aff
Revises: 6bb043ae2e58
Create Date: 2025-11-12 17:44:56.854968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f17f5399aff'
down_revision: Union[str, Sequence[str], None] = '6bb043ae2e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryitem',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('inventorytransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventoryitem.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventorytransaction')
    op.drop_table('inventoryitem')
    # ### end Alembic commands ###
