"""add user role

Revision ID: e163a994b7c8
Revises: d331b85686e2
Create Date: 2025-11-12 16:53:07.785858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e163a994b7c8'
down_revision: Union[str, Sequence[str], None] = 'd331b85686e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('role', sa.String(length=50), nullable=False, server_default='sales'),
    )
    op.execute("UPDATE \"user\" SET role='sales' WHERE role IS NULL")
    op.alter_column('user', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
